// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ArchiveProduct(arg1:string):Promise<void>;

export function CancelInventorySession(arg1:number):Promise<void>;

export function CloseInventorySession(arg1:number,arg2:Array<number>):Promise<void>;

export function DeleteLocation(arg1:number):Promise<void>;

export function EmitScannerStatus():Promise<void>;

export function ExportInventoryCSV():Promise<string>;

export function ExportInventoryCSVFile():Promise<string>;

export function ExportInventorySessionCSV(arg1:number):Promise<string>;

export function ExportInventorySessionCSVFile(arg1:number):Promise<string>;

export function GetActiveInventorySession():Promise<main.InventorySession>;

export function GetAllLocations():Promise<Array<main.Location>>;

export function GetAllProducts():Promise<Array<main.Product>>;

export function GetAvailablePorts():Promise<Array<string>>;

export function GetCurrentPort():Promise<string>;

export function GetScannerStatus():Promise<main.ScannerStatusPayload>;

export function ListCompletedInventorySessions():Promise<Array<main.InventorySession>>;

export function ListInventoryProducts(arg1:boolean):Promise<Array<main.Product>>;

export function ListInventorySessionItems(arg1:number):Promise<Array<main.InventorySessionItem>>;

export function ProcessBarcode(arg1:string):Promise<main.ScanPayload>;

export function RecordBatchCount(arg1:number,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function RecordInventoryScan(arg1:number,arg2:string,arg3:string):Promise<main.InventorySessionItem>;

export function RestoreProduct(arg1:string):Promise<void>;

export function SaveLocation(arg1:main.Location):Promise<void>;

export function SaveProduct(arg1:main.Product):Promise<void>;

export function SearchBarcode(arg1:string):Promise<main.Product>;

export function SearchProducts(arg1:string):Promise<Array<main.Product>>;

export function SetScannerPort(arg1:string):Promise<void>;

export function StartInventorySession(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.InventorySession>;

export function UndoLastCount(arg1:number):Promise<void>;

export function UpdateProductLocation(arg1:string,arg2:string):Promise<void>;
